In [ ]:
# Import the needed libraries

**72. How to swap two rows of an array?** 

In [6]:
import numpy as np
array= np.array([[1, -65, 5], [2, 3, 5],[52, 2, -1]])
row1_copy= array[1,:].copy()
row2_copy= array[2,:].copy()
array[1,:]= row2_copy
array[2,:]= row1_copy
print(array)


[[  1 -65   5]
 [ 52   2  -1]
 [  2   3   5]]


**75. How to compute averages using a sliding window over an array?**

In [18]:
array= np.array([1, -65, 52, 3, 5, 2, 2, -1])
numbers= np.arange(1, 9)


print(np.divide(array, numbers))

[  1.         -32.5         17.33333333   0.75         1.
   0.33333333   0.28571429  -0.125     ]
